### ISSUE TITLE
Data is not loading from service.

### ISSUE THREAD

**Issue by theromie** [NicholasAzar/ng-selectize#26] opened 2017-03-01 12:23 UTC
sport.ts
`export interface Sport {
	id: number;
	name: string;
}`

sportservice.ts
`export class SportService {
  getSport(): Promise<Sport[]> {
    return Promise.resolve(SPORTS);
  } 
}`

component.ts
`
options: Sport[] =[];
config: any = {   
    create: true, 
    maxItems: 5,
    plugins:["dropdown_direction","remove_button"]
  };
placeholder: string = 'Search Sports';
getSports() {    
   this.sportservice.getSport().then(results=> this.options = results);
}
call getSports() in OnInit()
`

component.html
`<ng2-selectize [config]="config" [options]="options" [placeholder]="placeholder" [(ngModel)]="sports" name="sports" ngDefaultControl></ng2-selectize>`

**Comment by NicholasAzar** [comment] 2017-03-03 02:46
Hi @theromie, i'll take a look at this and let you know soon

**Comment by NicholasAzar** [comment] 2017-03-03 02:58
@theromie I couldn't reproduce any issues with this, seemed to work ok as far as I could tell. I committed the example to https://github.com/NicholasAzar/ng-selectize-demo/commit/7d284b7d03b963f00b21b059d3da0eddc3f8a461 if you want to compare yours against it. Closing this for now.

**Closed** 2017-03-03 02:59 UTC
